############ What is a service account? ##############################
# A service account provides an identity for processes that run in a Pod
#
# When you create a pod, if you do not specify a service account, it is automatically assigned the
# default service account in the same namespace. If you get the raw json or yaml for a pod you have
# created (for example, kubectl get pods/<podname> -o yaml), you can see the spec.serviceAccountName
# field has been automatically set.

########### Get details of a service account ######################
# list service account of a namespace
# kubectl get serviceaccounts

# Get info of a serviceaccounts
# kubectl get serviceaccounts/build-robot -o yaml


apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-submit-robot
  namespace: user-pengfei