# we can also redirect the query to another url
# In this example, we create a ingress service which redirect all queries from re-ingress.kub.sspcloud.fr to test-ingress.kub.sspcloud.fr
# because re-ingress does not match any k8s service. So it does not have the http.path.* to specify the matched k8s service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: https://test-ingress.kub.sspcloud.fr
spec:
# This tls config makes the ingress backend generate tls resolution for your service
  tls:
    - hosts:
        - re-ingress.kub.sspcloud.fr
  rules:
  # specify the url of your ingress service
    - host: re-ingress.kub.sspcloud.fr
           