apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: flow-use-print-message-template
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
      - - name: invoke-print-message-template
          templateRef:
            name: print-message-template
            template: main
          arguments:
            parameters:
            - name: message
              value: "hello world"