apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: flow-call-entire-template-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: message
        value: "from workflow"
  workflowTemplateRef:
    name: print-message-template