# The workflow template definition in argo v2.7 and after are fully compatible with Workflow definitions. 
# You only need to change kind: Workflow to kind: WorkflowTemplate to convert existing Workflow to a WorkflowTemplate.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: print-message-template
spec:
  entrypoint: main
  # This template has an exit handler
  onExit: exit-handler
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
      container:
        image: busybox
        args: ["echo", "{{inputs.parameters.message}}"]
        imagePullPolicy: IfNotPresent
   # exit handler template
    - name: exit-handler
      container:
        image: busybox
        args: ["echo", "Exit Handler"]
        imagePullPolicy: IfNotPresent

# To submit a workflow template
# argo template create path/to/template.yaml