apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: flow-with-simple-cron
spec:
  # schedule defines how the job repeats, it uses the same syntax as the linux crontab syntax, 
  # the five star is in order of [Minute] [Hour] [Day_of_the_Month] [Month_of_the_Year] [Day_of_the_Week],
  # Note in the new linux release, you can add an optional six star to fefine year.
  # 1: */2 means every two mins. If you want every min after 6 min, you write 6/1. 8/2 means every 2 min after 8 min
  # As a result, the two numbers must in range of [0,59]
  # 2: For hours, the two numbers must in range of [0,23]
  # 3: For day of the month, the two numbers must in range of [1,31] 
  # 4: For month of year, the two numbers must in range of [1,12]
  # For day of the week, the two number must in range of [0,7], where 0 and 7 means Sunday
  # "* * * * *" means the job will be running every second, every min, every hour, every
  schedule: "*/3 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: whalesay
    templates:
    - name: whalesay
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["date; sleep 90"]