# DaemonSets are used to ensure that some or all of your K8S nodes run a copy of a pod, which allows you to run a daemon on every node.
# This example deploys a fluentd-elasticsearch image that will run on every node. This daemonset will deploy the image on every node 
# collecting logs and sending them to ES.

apiVersion: apps/v1 #required fields
kind: DaemonSet #required fields
metadata: #required fields
  name: fluentd-es-demo
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-es #this must match the label below
  template: #required fields 
    metadata:
      labels:
        name: fluentd-es #this must match the selector above
    spec:
    # this toleration is to have the daemonset runnable on master nodes
    # remove it if your masters can't run pods
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-es-example
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        emptyDir: {}
      - name: varlibdockercontainers
        emptyDir: {}
      