# With Argo, you can use any container image that you like to generate any kind of artifact. 
# In practice, however, we find certain types of artifacts are very common, so there is built-in 
# support for :
# - git
# - http 
# - gcs
# - s3
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hardwired-artifact-
spec:
  entrypoint: hardwired-artifact
  templates:
  - name: hardwired-artifact
    inputs:
      artifacts:
      # Check out the master branch of the argo repo and place it at /src
      # revision can be anything that git checkout accepts: branch, commit, tag, etc.
      - name: git-source
        path: /src
        git:
          repo: https://github.com/argoproj/argo.git
          revision: "master"
          
      # Download kubectl 1.8.0 and place it at /bin/kubectl
      - name: http-source
        path: /bin/kubectl
        mode: 0755
        http:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl

      # Copy an s3 compatible artifact repository bucket (such as AWS, GCS and Minio) and place it at /s3
      # all the attributes under s3 is madatory. if you miss one the workflow is not validated.
      - name: s3-source
        path: /s3
        s3:
          endpoint: minio.lab.sspcloud.fr
          bucket: argo-artifacts
          key: tmp
          accessKeySecret:
            name: prod-minio-cred
            key: accessKey
          secretKeySecret:
            name: prod-minio-cred
            key: secretKey
    container:
      image: debian
      command: [sh, -c]
      args: ["ls -l /src /bin/kubectl /s3"]