apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atlas.fullname" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "atlas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "atlas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "atlas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: [
                    "/bin/bash",
                    "-c",
                    "/opt/apache-atlas-2.1.0/bin/atlas_start.py;
                    "
                    ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 21000
              protocol: TCP
          volumeMounts:
          - name: atlas-config
            mountPath: /opt/apache-atlas-2.1.0/conf/atlas-application.properties
            subPath: atlas-application.properties
          - name: atlas-config
            mountPath: /opt/apache-atlas-2.1.0/conf/keycloak.json
            subPath: keycloak.json
          - name: atlas-config
            mountPath: /opt/apache-atlas-2.1.0/conf/sspcloud-authorization-policy.json
            subPath: sspcloud-authorization-policy.json
          - name: atlas-data-volume
            mountPath: /opt/apache-atlas-2.1.0/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: atlas-config
          configMap:
            name: {{ .Release.Name }}-atlas-cm
        - name: atlas-data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-atlas-data-claim
