# To declare input in a workflow, we use keyword "arguments", which are passed in to the entry point template. 
# A template uses keyword "inputs" which are then provided by template callers (such as steps, dag, or even a workflow).
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  # invoke the woker1 template with
  # global-message as the argument
  # to the message parameter
  entrypoint: worker1
  arguments:
    parameters:
    - name: global-message
      value: value of workflow parameter

  templates:
  - name: worker1
  # you can also define parameter inside a template, it starts with keyword "inputs"
    inputs:
      parameters:
      - name: local-message       # parameter declaration
        value: value of template parameter
    container:
      image: busybox
      # run echo command with that message input parameter as args
      command: ["echo"]
      # invoke the parameter defined in argument section in container
      args: ["{{inputs.parameters.local-message}}, {{workflow.parameters.global-message}} "]

# Try to change both the global-message and local-message to message. You can notice the template locale parameter will be 
# overwriten by the workflow global parameter's value.  

# As a result, do not mix the name of workflow parameter and template parameter 

############## Enter params with argo submit #####################
# You can also pass parameters with the command line client
# argo submit flow_with_params.yaml -p 'global-message="value from cli"' --watch