apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: call-shell-executor-{{ .Release.Name }}
spec:
  arguments:
    parameters:
      - name: {{.Values.workflow.param.name}}
        value: {{.Values.workflow.param.value}}
  workflowTemplateRef:
    name: {{.Values.workflow.templateName}}