apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-postgres-configmap
  labels:
    app: mlflow-postgres
data:
  POSTGRES_DB: defaultdb
  POSTGRES_USER:
  POSTGRES_PASSWORD: mlflow_pwd
  PGDATA: /var/lib/postgresql/mlflow/data