apiVersion: v1
kind: Pod
metadata:
  name: pod-with-init-container
  labels:
    app: pod-with-init-container
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"

  initContainers:
  # The first init container will check if a service called "pengfei-fake-service" is available in the default namespace
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', "until nslookup pengfei-fake-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
 # The second init container will check if a service called "pengfei-fake-db" is available in the default namespace
  - name: init-mydb
    image: busybox
    command: ['sh', '-c', "until nslookup pengfei-fake-db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]