apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  # invoke the woker1 template with
  # "hello ..." as the argument
  # to the message parameter
  entrypoint: worker1
  arguments:
    parameters:
    - name: message
      value: hello pengfei, this is my first parameter

  templates:
  - name: worker1
  # before you can use the parameter, you need to declare it in the template
    inputs:
      parameters:
      - name: message       # parameter declaration
    container:
      image: busybox
      # run echo command with that message input parameter as args
      command: ["echo"]
      # invoke the parameter defined in argument section in container
      args: ["{{inputs.parameters.message}}"]
      