# To limit the elapsed time for a workflow, you can set the variable activeDeadlineSeconds
# In this example, we set a timeout of 10 sec for a container template
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: flow-with-timeouts-
spec:
  entrypoint: sleep
  templates:
  - name: sleep
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo sleeping for 1m; sleep 60; echo done"]
    activeDeadlineSeconds: 10           # terminate container template after 10 seconds