apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret1
spec:
  containers:
  - name: mypod
    image: busybox
    command: [ "/bin/sh","-c","sleep 600" ]
    volumeMounts:
    - name: creds
      mountPath: "/etc/creds"
      readOnly: true
  # create a volume named creds
  volumes:
  - name: creds
  # get data from secret pengfei-basic-auth
    secret:
      secretName: pengfei-basic-auth
      # defaultMode defines the default file acl.
      defaultMode: 0400
      items:
      # for key value pair username, create a file my-group/my-username
      - key: username
        path: my-group/my-username
        # If default acl is not ok, we can overwrite it by using mode
        mode: 0777
      - key: password
        path: my-group/my-password