apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
  # suppose roc is a private docker registry which requires auth
    image: roc/test
  # here we can put the registrykey secret to auth with the private docker registry
  imagePullSecrets:
    - name: myregistrykey
