# This version creates each job as part of the workflow, and limits concurrent jobs using
# `spec.parallelism`
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: backfill-v2
spec:
  entrypoint: main
  # limit to one job at a time
  parallelism: 1
  templates:
    - name: main
      steps:
        - - name: create-job
            templateRef:
              name: print-date-cluster-template
              template: main
            arguments:
              parameters:
                - name: date
                  value: "{{item}}"
            withSequence:
              # run for the 19th to the 21st
              start: "19"
              end: "21"
              format: "2020-05-%02X"