# This version will create jobs as fast as it can, and allow them to run and complete in parallel
# Use this when you do not have parallelism limits. It may use all your k8s cluster resource.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cronflow-backfill-v1
spec:
  entrypoint: main
  # the backfill must use a service account which can call argo workflow api and create workflows
  # you should not - despite this example - use the "argo-server" service account
  serviceAccountName: argo-server
  templates:
    - name: main
      steps:
        - - name: day
            template: create-job
            arguments:
              parameters:
                - name: date
                  value: "{{item}}"
            withSequence:
              # run for the 19th to the 21st
              start: "19"
              end: "21"
              format: "2020-05-%02X"
    - # the template which creates actual workflow
      name: create-job
      inputs:
        parameters:
          - name: date
      resource:
        action: apply
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            # using a name based on the date prevents re-creating resources,
            # making this more robust
            name: job-{{inputs.parameters.date}}
          spec:
            entrypoint: main
            templates:
              - name: main
                steps:
                  - - name: start-job
                      arguments:
                        parameters:
                          - name: date
                            value: "{{inputs.parameters.date}}"
                      templateRef:
                        name: job
                        template: main