apiVersion: apps/v1
kind: Deployment
metadata:
  # define the name of this deployment
  name: cassandra-client
  # define a label of this deployment, usefull to group a set of deployment
  labels: 
    app: cassandra-client
# spec of the deployment
spec:
  # defines which template this deployment uses, it must match the template(i.e. pod) label
  selector:
    matchLabels:
      app: cassandra-client
  # number of the replicas of the pod    
  replicas: 1
  # template(i.e. description) of the pod
  template:
    metadata:
      # label of the pod
      labels:
        app: cassandra-client
    spec:
      containers:
        # no 1 container of the pod
      - name: client
        image: docker.io/bitnami/cassandra:3.11.9-debian-10-r30
        # set the limit of the pod resource, by default there is no limit
        env:
          - name: CASSANDRA_PASSWORD
            value: "Qlyf6b5XpT"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always