apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  labels: 
   app: pengfei-job-test    
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  # A job's spec are immutable, we can't change them after job creation. We need to delete old job, and submit new job.
  # completions default value is 1, it means if 1 pod complete and return 0. The job is considered finished succesfully.
  completions: 4
  # parallelism default value is 1, it means 1 pod can run in parallel. 
  parallelism: 2
  # set a dead line to retry the job. 
  activeDeadlineSeconds: 100
  # auto remove the job after the job finished 
  ttlSecondsAfterFinished: 150
  backoffLimit: 4