##################### work avoidance. #######################################
# A workflow that utilizes this is simply a workflow containing steps that do not run if the work has already
# been done. This simplest way to do this is to use marker files.
# Use cases:
# - An expensive step appears across multiple workflows - you want to avoid repeating them.
# - A workflow has unreliable tasks - you want to be able resubmit the workflow.


# This example shows how to use a PVC and optional input artifacts to avoid work.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: work-avoidance-
spec:
  entrypoint: main
# Create a pvc for the workflow
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi

  onExit: save-markers
# workflow has two main step, load-marker and echo
  templates:
    - name: main
      steps:
        - - name: load-markers
            template: load-markers
        - - name: echo
            template: echo
            arguments:
              parameters:
                - name: num
                  value: "{{item}}"
            withSequence:
              count: "3"
# step 1: load-marker read file markers from s3 artifact and write them to pvc
    - name: load-markers
      inputs:
        artifacts:
          - name: markers
            path: /work/markers
            optional: true
            s3:
              key: work-avoidance-markers
              bucket: argo-artifacts
              endpoint: minio.lab.sspcloud.fr
              accessKeySecret:
                name: prod-minio-cred
                key: accessKey
              secretKeySecret:
                name: prod-minio-cred
                key: secretKey
      container:
        image: docker/whalesay:latest
        command:
          - mkdir
          - -p
          - /work/markers
        volumeMounts:
          - name: work
            mountPath: /work
# Step 2: create file marker based on date and parameter
    - name: echo
      inputs:
        parameters:
          - name: num
      script:
        image: docker/whalesay:latest
        command:
          - bash
          - -eux
        source: |
          marker=/work/markers/$(date +%Y-%m-%d)-echo-{{inputs.parameters.num}}
          if [ -e  ${marker} ]; then
            echo "work already done"
            exit 0
          fi
          echo "working very hard"
          # toss a virtual coin and exit 1 if 1
          if [ $(($(($RANDOM%10))%2)) -eq 1 ]; then
            echo "oh no!"
            exit 1
          fi
          touch ${marker}
        volumeMounts:
          - name: work
            mountPath: /work
# onExit step write the file marker to s3
    - name: save-markers
      container:
        image: docker/whalesay:latest
        command:
          - "true"
        volumeMounts:
          - name: work
            mountPath: /work
      outputs:
        artifacts:
          - name: markers
            path: /work/markers
            s3:
              key: work-avoidance-markers
              bucket: argo-artifacts
              endpoint: minio.lab.sspcloud.fr
              accessKeySecret:
                name: prod-minio-cred
                key: accessKey
              secretKeySecret:
                name: prod-minio-cred
                key: secretKey