apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: write-simple-marker-files-to-s3-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: marker-file-name
        value: 2021-02-16-echo-0
      - name: argo-path
        value: tmp
  templates:
    - name: main
      container:
        image: busybox
        command: [sh, -c]
        args: ["touch /tmp/{{workflow.parameters.marker-file-name}}"]
        volumeMounts:
          - name: out
            mountPath: /tmp
      # create an empty volume to output the artifacts
      volumes:
        - name: out
          emptyDir: { }
      outputs:
        artifacts:
          - name: message
            path: /tmp
            s3:
              endpoint: minio.lab.sspcloud.fr
              bucket: argo-artifacts
              # we need to add "" to ask argo evaluate the template expression
              key: "{{workflow.parameters.argo-path}}/{{workflow.parameters.marker-file-name}}.tgz"
              accessKeySecret:
                name: prod-minio-cred
                key: accessKey
              secretKeySecret:
                name: prod-minio-cred
                key: secretKey