apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: flow-with-condition-in-dag-
spec:
  entrypoint: coinflip
  templates:
  - name: coinflip
    dag:
      tasks: 
      - name: generate-condition
        template: gen-condition
      - name: heads
        dependencies: [generate-condition]
        template: heads
        when: "{{tasks.generate-condition.outputs.result}} == heads"
      - name: tails
        dependencies: [generate-condition]
        template: tails
        when: "{{tasks.generate-condition.outputs.result}} == tails"


# Return heads or tails based on a random number
  - name: gen-condition
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)

  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]

  - name: tails
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was tails\""]  