apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: check-data-quality
spec:
  # The default entry point is get shape
  entrypoint: check-data-shape-wt
  templates:
    - name: check-data-shape-wt
      inputs:
        parameters:
          - name: input-data-path
          - name: volume-name
        container:
          image: liupengfei99/python38-ds
          command: [sh, -c]
          args: ["python -V && python /mnt/bin/src/data_info/CheckShape.py
               {{inputs.parameters.input-data-path}}"]
          volumeMounts:
            - name: {{inputs.parameters.input-data-path}}
              mountPath: /mnt

#    - name: backup
#      inputs:
#        parameters:
#          - name: message
#      container:
#        image: busybox
#        args: ["echo", "backup template prints {{inputs.parameters.message}}"]
#        imagePullPolicy: IfNotPresent
#   # exit handler template
#    - name: exit-handler
#      container:
#        image: busybox
#        args: ["echo", "Exit Handler"]
#        imagePullPolicy: IfNotPresent

# To submit a workflow template
# argo template create path/to/template.yaml