apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        artifacts:
          # Check out the master branch of the argo repo and place it at /src
          # revision can be anything that git checkout accepts: branch, commit, tag, etc.
          - name: git-source
            path: /bin
            git:
              repo: https://github.com/pengfei99/argoDataPipeline.git
              revision: "main"
      container:
        image: debian
        command: [sh, -c]
        args: ["ls -l /bin"]
