apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pokemon-workflow-v3-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: output-file-list
        value: |
          [
            { "file-path": "/mnt/tmp", "file-name": "pokemon-enriched.csv" }
          ]
  workflowTemplateRef:
    name: pokemon-workflow-template
    clusterScope: true