apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: s3-input-output-template
spec:
  entrypoint: s3-output
  templates:
    - name: s3-output
      inputs:
        parameters:
          - name: file-name
          - name: file-path
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo save {{inputs.parameters.file-path}}/{{inputs.parameters.file-name}}
                      to s3://minio.lab.sspcloud.fr/argo-artifacts/tmp/;
                      cp {{inputs.parameters.file-path}}/{{inputs.parameters.file-name}}
                         /tmp/{{inputs.parameters.file-name}}"]
        volumeMounts:
          - name: workflow-tmp
            mountPath: /mnt
          - name: out
            mountPath: /tmp
        # k8sapi executor does not support outputs from base image laye, have to use a emptyDir
      volumes:
        - name: out
          emptyDir: { }
      outputs:
        artifacts:
          - name: output-file
            path: "/tmp/{{inputs.parameters.file-name}}"
            s3:
              endpoint: minio.lab.sspcloud.fr
              bucket: argo-artifacts
              key: "tmp/{{inputs.parameters.file-name}}.tgz"
              accessKeySecret:
                name: prod-minio-cred
                key: accessKey
              secretKeySecret:
                name: prod-minio-cred
                key: secretKey