---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pods-manager
  namespace: user-pengfei

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-manager
  namespace: user-pengfei
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-manager
  namespace: user-pengfei
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-manager
subjects:
  - kind: ServiceAccount
    name: pods-manager