# The pods which runs jupyter has a generated service account, and a role binding, which binds the sa to cluster-role
# called admin. That's why it can create pods
# kubectl describe ClusterRole/admin

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: spark-runner
  namespace: user-pengfei

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-runner-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: spark-runner
    namespace: user-pengfei
