apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-env
spec:
  containers:
  - name: mypod
    image: busybox
    command: [ "/bin/sh","-c","sleep 600" ]
    env:
    # Specify env var name
      - name: SECRET_USERNAME
      # specify the source value
        valueFrom:
        # name of the secret
          secretKeyRef:
            name: pengfei-basic-auth
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pengfei-basic-auth
            key: password
  restartPolicy: Never