apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-env
spec:
  containers:
    - name: mypod
      image: busybox
      command: [ "/bin/sh","-c","sleep 600" ]
      # Specify env var name
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Never