# note the name of this file is mandatory. it must be kustomization.yaml. 
# and the command kubectl apply -k <directory-name> only takes the name of the directory which contains kustomization.yaml
configMapGenerator:
- name: game-config-4
  files:
  # from files
  - /home/pliu/git/k8s/tutos/l06_configMap/game-config/game.properties
  - /home/pliu/git/k8s/tutos/l06_configMap/game-config/ui.properties
  # from files with custom keys, the default value of the key is the name of the file
  - pengfei-game=/home/pliu/git/k8s/tutos/l06_configMap/game-config/game.properties
  # from literals
  literals:
  - special.how=very
  - special.type=charm


  
  