apiVersion: v1
kind: Pod
metadata:
  name: configmap-vol-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      # let the container sleep for 600 sec to keep it running. So we can do kubectl exec on the container
      command: [ "/bin/sh","-c","sleep 600" ]
      # mount an existing volume on the container 
      volumeMounts:
      - name: pengfei-volume
        mountPath: /etc/config
  # create a volume by using the config map
  volumes:
    # name of the volume
    - name: pengfei-volume
      configMap:
        # name of the config map
        name: game-config
        items:
          # key name
        - key: game.properties
          # path of the file which will contain the value of the key
          path: game.properties
        - key: ui.properties
          path: ui.properties
  restartPolicy: Never