apiVersion: v1
kind: Pod
metadata:
  name: redis-server-cm-test
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.8"
    volumeMounts:
    # mount a volume(folder) named data under /redis-master-data
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
  # create a volume data from an empty dir
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-config-cm-kt4tk569kg
        items:
        - key: pengfei-redis-config
          path: redis.conf