apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: call-spark-submit-template-
spec:
  # Specify an entry point which will override the default entrypoint of the WorkflowTemplate
  entrypoint: main
  arguments:
    parameters:
      - name: message
        value: "from workflow"
  workflowTemplateRef:
    name: spark-submit-template